### ISSUE TITLE
Promise does not resolve for invalid routes

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-ekko#34]
``` bash
[15:23:57] [av-ekko] GET /api/v1/organizations/undefined 404 0.496
Warning: a promise was created in a handler but was not returned from it
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by robmcguinness** [comment]
https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it
